# -*- coding: utf-8 -*-
# Generated by Django 1.18.17 on 2017-04-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nyt', '0009_add_last_sent_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='interval',
            field=models.SmallIntegerField(default=0, verbose_name='interval', choices=[(-1, 'never'), (0, 'instantly'), (1380, 'daily'), (9660, 'weekly')]),
        ),
    ]
